import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container2: {
    flex: 8,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    //backgroundColor: '#FFFFFF',
  },
  checkbox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#00AA22',
  },
  input: {
    height: 40,
    width: '70%',
    maxWidth: '80%',
    marginLeft: 8,
    borderWidth: 1,
    borderRadius: 20,
    padding: 10,
    color: '#000000',
  },
  titulo: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F4E79',
  },
  tabela: {
    fontWeight: 'bold',
    alignItems: 'center',
    width: '100%',
  },
  radio: {
    fontWeight: 'bold',
    flexDirection: 'row',
    margin: 0,
    marginBottom: '5%',
    //alignItems: 'center',
  },
  header: {
    //backgroundColor: '#FFC000',
    //color: '#1F4E79',
    fontWeight: 'bold',
    //borderWidth: 2,
    //paddingLeft: "10%",
    flexDirection: 'row',
    //justifyContent: 'center',
    alignItems: 'center',
  },
  texto: {
    fontSize: 15,
    color: '#000000',
  },
  textofec: {
    fontSize: 15,
    color: '#000000',
    width: '25%',
    margin: 0,
  },
  strokeColorButton: {
    marginHorizontal: 2.5,
    marginVertical: 8,
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  strokeWidthButton: {
    marginHorizontal: 2.5,
    marginVertical: 8,
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#39579A',
  },
  functionButton: {
    marginHorizontal: 2.5,
    marginVertical: 8,
    height: 30,
    width: 60,
    backgroundColor: '#39579A',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
});
